version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
    db:
      image: mysql:5.7
      ports:
        - "32000:3307"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro