version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
    db:
      image: mysql:5.7
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: currencies
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      volumes:
        - ./docker/data/db:/var/lib/mysql