version: '2'

networks:
  default:
    external:
      name: basicwebsite_backend

services:
    web:
        build: .
        ports:
          - "5000:5000"
        volumes:
          - .:/code
        external_links:
          - basicwebsite_mysql_1:mysql
        
    